# This file is part of the Sylius package.
# (c) Sylius Sp. z o.o.

sylius_payment:
    resources:
        gateway_config:
            classes:
                model: Sylius\Bundle\PayumBundle\Model\GatewayConfig
                interface: Sylius\Bundle\PayumBundle\Model\GatewayConfigInterface

sylius_payum:
    gateway_config:
        validation_groups:
            paypal_express_checkout:
                - 'sylius'
                - 'sylius_paypal_express_checkout'
            stripe_checkout:
                - 'sylius'
                - 'sylius_stripe_checkout'
